# Generated by Django 6.1.1 on 2026-09-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_icon_remove_store_address_remove_store_social_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeaddress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storecolor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storecontact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storeservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storesociallink',
            options={'ordering': ['-created_at']},
        ),
    ]
