# Generated by Django 6.1.1 on 2026-09-25 23:34

import django.utils.timezone
from datetime import timedelta

from django.db import migrations, models


def backfill_created_at(apps, schema_editor):
    """
    Pre-existing icons would otherwise all share the migration's timestamp,
    leaving their -created_at order (and so get-all pagination) arbitrary -
    space them a second apart in id order instead, newest = highest id.
    """
    Icon = apps.get_model("stores", "Icon")
    now = django.utils.timezone.now()
    icons = list(Icon.objects.order_by("-id"))
    for offset, icon in enumerate(icons):
        icon.created_at = now - timedelta(seconds=offset)
    Icon.objects.bulk_update(icons, ["created_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_storeaddress_options_alter_storecolor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='icon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(backfill_created_at, migrations.RunPython.noop),
    ]
