# Generated by Django 6.1.1 on 2026-09-20 20:07

import buyers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
        ('products', '0010_alter_storecategory_options_and_more'),
        ('stores', '0003_alter_storeaddress_options_alter_storecolor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='avatar_photo',
            field=models.ImageField(blank=True, null=True, upload_to=buyers.models.buyer_avatar_upload_path),
        ),
        migrations.AddField(
            model_name='buyer',
            name='avatar_photo_processed',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=buyers.models.buyer_avatar_processed_upload_path),
        ),
        migrations.AddField(
            model_name='buyer',
            name='avatar_processing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='buyer',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_buyers', to='products.storeproduct'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='favorite_stores',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_buyers', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='buyer',
            index=models.Index(fields=['avatar_processing_status', 'updated_at'], name='buyers_buye_avatar__e0e0b8_idx'),
        ),
    ]
