# Generated by Django 6.1.1 on 2026-09-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyer_avatar_photo_buyer_avatar_photo_processed_and_more'),
        ('products', '0011_storeproduct_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerFavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_events', to='products.storeproduct')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='favorite_products',
        ),
        migrations.AddField(
            model_name='buyer',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_buyers', through='buyers.BuyerFavoriteProduct', to='products.storeproduct'),
        ),
        migrations.AddConstraint(
            model_name='buyerfavoriteproduct',
            constraint=models.UniqueConstraint(fields=('buyer', 'product'), name='uniq_buyer_favorite_product'),
        ),
    ]
