# Generated by Django 6.1.1 on 2026-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_buyerfavoriteproduct_alter_buyer_favorite_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='avatar_processing_retries',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
