# Generated by Django 6.1.1 on 2026-09-21 22:05

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0003_buyerfavoriteproduct_alter_buyer_favorite_products_and_more'),
        ('products', '0012_storeproductview'),
        ('stores', '0003_alter_storeaddress_options_alter_storecolor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending_confirmation', max_length=30)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='buyers.buyer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_snapshot', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('quantity', models.PositiveIntegerField()),
                ('price_type', models.CharField(choices=[('sale', 'Sale'), ('rental', 'Rental'), ('tailoring', 'Tailoring')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('applied_discount', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.storeorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.storeproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
