# Generated by Django 6.1.1 on 2026-09-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'Buyer changed their mind'), ('found_better_price', 'Found a better price elsewhere'), ('ordered_by_mistake', 'Ordered by mistake'), ('delivery_too_slow', 'Delivery is taking too long'), ('out_of_stock', 'Product out of stock'), ('cannot_fulfill', 'Store cannot fulfill the order'), ('buyer_unreachable', 'Could not reach the buyer'), ('suspected_fraud', 'Suspected fraudulent order'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('store', 'Store')], max_length=10, null=True),
        ),
    ]
