# Generated by Django 6.1.1 on 2026-10-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_storeorder_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorderitem',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
