# Generated by Django 6.1.1 on 2026-09-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_icon_remove_store_address_remove_store_social_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.storecategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('price_rental', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('price_tailoring', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_rentable', models.BooleanField(default=False)),
                ('blur_image_in_site', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_in_category', to='products.storecategory')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stores.storecolor')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_subcategory', to='products.storecategory')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_photos/%Y/%m/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photos', models.ManyToManyField(blank=True, related_name='variants', to='products.storeproductphoto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.storeproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.storetag'),
        ),
        migrations.AddConstraint(
            model_name='storecategory',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_category_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='storetag',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_tag_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='uniq_product_slug_per_store'),
        ),
    ]
