# Generated by Django 6.1.1 on 2026-09-20 17:14

import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductphoto',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storeproductphoto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='storeproductphoto',
            name='image',
            field=models.ImageField(upload_to=products.models.product_photo_upload_path),
        ),
    ]
