# Generated by Django 6.1.1 on 2026-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_storeproductphoto_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='manufacture',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='material',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
