# Generated by Django 6.1.1 on 2026-09-20 18:12

import django.db.models.deletion
import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_storeproduct_manufacture_storeproduct_material'),
        ('stores', '0002_icon_remove_store_address_remove_store_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductphoto',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StoreProductPhotoRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quality', models.CharField(choices=[('medium', 'Medium (720p)'), ('small', 'Small (360p)')], max_length=20)),
                ('image', models.ImageField(upload_to=products.models.photo_rendition_upload_path)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='products.storeproductphoto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photo_renditions', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('photo', 'quality'), name='uniq_rendition_quality_per_photo')],
            },
        ),
    ]
