# Generated by Django 6.1.1 on 2026-09-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_storeproductphoto_processing_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductphotorendition',
            name='uuid',
        ),
    ]
