# Generated by Django 6.1.1 on 2026-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_storeproductphotorendition_uuid'),
        ('stores', '0002_icon_remove_store_address_remove_store_social_links_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storeproductphoto',
            index=models.Index(fields=['processing_status', 'updated_at'], name='products_st_process_6fc2e8_idx'),
        ),
    ]
