# Generated by Django 6.1.1 on 2026-09-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_storeproductphoto_products_st_process_6fc2e8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductphotorendition',
            name='quality',
            field=models.CharField(choices=[('large', 'Large (1080p, WebP)'), ('medium', 'Medium (720p, WebP)'), ('small', 'Small (320p, WebP)')], max_length=20),
        ),
    ]
