# Generated by Django 6.1.1 on 2026-09-20 18:52

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_storeproductphotorendition_quality'),
        ('stores', '0002_icon_remove_store_address_remove_store_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.category_cover_upload_path),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='cover_processed',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=products.models.category_cover_processed_upload_path),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='cover_processing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default=None, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['cover_processing_status', 'updated_at'], name='products_st_cover_p_a132f7_idx'),
        ),
    ]
