# Generated by Django 6.1.1 on 2026-09-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_storecategory_cover_storecategory_cover_processed_and_more'),
        ('stores', '0002_icon_remove_store_address_remove_store_social_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreDiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('fixed_amount', 'Fixed amount'), ('percentage', 'Percentage')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_products', to='products.storediscount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='products.storeproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_products', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='storediscount',
            name='products',
            field=models.ManyToManyField(related_name='discounts', through='products.StoreDiscountProduct', to='products.storeproduct'),
        ),
        migrations.AddConstraint(
            model_name='storediscountproduct',
            constraint=models.UniqueConstraint(fields=('discount', 'product'), name='uniq_product_per_discount'),
        ),
    ]
