# Generated by Django 6.1.1 on 2026-09-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_storediscount_storediscountproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storecategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storediscount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storediscountproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storeproductphoto',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storeproductphotorendition',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storeproductvariant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storetag',
            options={'ordering': ['-created_at']},
        ),
    ]
