# Generated by Django 6.1.1 on 2026-09-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_storecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
