# Generated by Django 6.1.1 on 2026-09-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_storeproduct_views'),
        ('stores', '0003_alter_storeaddress_options_alter_storecolor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='products.storeproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['product', 'created_at'], name='products_st_product_cfee64_idx')],
            },
        ),
    ]
