# Generated by Django 6.1.1 on 2026-09-25 21:46

import django.db.models.deletion
from django.db import migrations, models


def copy_material_strings(apps, schema_editor):
    """Each distinct non-blank StoreProduct.material string becomes a per-store material row."""
    StoreProduct = apps.get_model("products", "StoreProduct")
    StoreProductMaterial = apps.get_model("products", "StoreProductMaterial")
    for product in StoreProduct.objects.exclude(material=""):
        name = product.material.strip()
        if not name:
            continue
        material, _ = StoreProductMaterial.objects.get_or_create(store_id=product.store_id, name=name)
        product.materials.add(material)


def restore_material_strings(apps, schema_editor):
    StoreProduct = apps.get_model("products", "StoreProduct")
    for product in StoreProduct.objects.prefetch_related("materials"):
        names = [m.name for m in product.materials.all()]
        if names:
            product.material = ", ".join(names)[:255]
            product.save(update_fields=["material"])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_storeproductview'),
        ('stores', '0003_alter_storeaddress_options_alter_storecolor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_material_categories', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='stores.store')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='products.storeproductmaterialcategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.storeproductmaterial'),
        ),
        migrations.AddConstraint(
            model_name='storeproductmaterial',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_product_material_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='storeproductmaterialcategory',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_product_material_category_name_per_store'),
        ),
        migrations.RunPython(copy_material_strings, restore_material_strings),
        migrations.RemoveField(
            model_name='storeproduct',
            name='material',
        ),
    ]
