# Generated by Django 6.1.1 on 2026-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_storeproductmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
