# Generated by Django 6.1.1 on 2026-10-02 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_storecategory_visible'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # A plain AlterField would emit `ALTER COLUMN size TYPE integer[]`,
            # which Postgres rejects without an explicit USING cast from the
            # old scalar column - existing single sizes become one-element
            # arrays, NULLs become empty arrays.
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE products_storeproduct "
                        "ALTER COLUMN size DROP DEFAULT, "
                        "ALTER COLUMN size TYPE integer[] "
                        "USING CASE WHEN size IS NULL THEN '{}' ELSE ARRAY[size] END, "
                        "ALTER COLUMN size SET DEFAULT '{}', "
                        "ALTER COLUMN size SET NOT NULL;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE products_storeproduct "
                        "ALTER COLUMN size DROP DEFAULT, "
                        "ALTER COLUMN size DROP NOT NULL, "
                        "ALTER COLUMN size TYPE integer "
                        "USING size[1];"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='storeproduct',
                    name='size',
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, default=list,
                    ),
                ),
            ],
        ),
    ]
