# Generated by Django 6.1.1 on 2026-10-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_storeproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storediscount',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='products.storeproductphoto'),
        ),
    ]
