# Generated by Django 6.1.1 on 2026-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_storediscount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='cover_processing_retries',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='storeproductphoto',
            name='processing_retries',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
