# Generated by Django 6.1.1 on 2026-10-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_dedupe_storeproduct_slugs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storeproduct',
            name='uniq_product_slug_per_store',
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
