services:
  postgres-salon-test:
    image: postgres:18
    container_name: postgres-salon-test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_salon_test:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer-salon-test:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer-salon-test
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres-salon-test:5432/${DB_NAME}
      LISTEN_PORT: 6432
      POOL_MODE: transaction
      AUTH_TYPE: scram-sha-256
      ADMIN_USERS: ${DB_USER}
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 20
    depends_on:
      postgres-salon-test:
        condition: service_healthy
    ports:
      - "127.0.0.1:6433:6432"

  redis-salon-test:
    image: redis:7-alpine
    container_name: redis-salon-test
    restart: unless-stopped
    volumes:
      - redis_data_test:/data
    command: redis-server --maxmemory 512mb --maxmemory-policy volatile-lru

  app:
    build: .
    container_name: salonBackendTest
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@pgbouncer-salon-test:6432/${DB_NAME}
      DB_HOST: pgbouncer-salon-test
      DB_PORT: 6432
    depends_on:
      postgres-salon-test:
        condition: service_healthy
      pgbouncer-salon-test:
        condition: service_started
    ports:
      - "127.0.0.1:8101:8000"
    volumes:
      - ./src:/app/src
      - app_secrets_test:/app/secrets

  celery-worker-test:
    build: .
    container_name: salonCeleryWorkerTest
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@pgbouncer-salon-test:6432/${DB_NAME}
      DB_HOST: pgbouncer-salon-test
      DB_PORT: 6432
    depends_on:
      postgres-salon-test:
        condition: service_healthy
      pgbouncer-salon-test:
        condition: service_started
      redis-salon-test:
        condition: service_started
    command: >
      uv run celery -A src.core.celery.celeryApp.celery_app worker --loglevel=info
    volumes:
      - ./src:/app/src

  celery-beat-test:
    build: .
    container_name: salonCeleryBeatTest
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@pgbouncer-salon-test:6432/${DB_NAME}
      DB_HOST: pgbouncer-salon-test
      DB_PORT: 6432
    depends_on:
      postgres-salon-test:
        condition: service_healthy
      pgbouncer-salon-test:
        condition: service_started
      redis-salon-test:
        condition: service_started
    command: >
      uv run celery -A src.core.celery.celeryApp.celery_app beat --loglevel=info
    volumes:
      - ./src:/app/src

volumes:
  postgres_data_salon_test:
  redis_data_test:
  app_secrets_test:
