# Generated by Django 6.1.1 on 2026-09-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_storeproduct_manufacture_storeproduct_material'),
        ('stores', '0002_icon_remove_store_address_remove_store_social_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('news_type', models.CharField(choices=[('event', 'Event'), ('discount', 'Discount'), ('holiday', 'Holiday'), ('other', 'Other')], max_length=20)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('products', models.ManyToManyField(blank=True, related_name='news_items', to='products.storeproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'store news',
                'constraints': [models.UniqueConstraint(fields=('store', 'slug'), name='uniq_news_slug_per_store')],
            },
        ),
    ]
