# Generated by Django 6.1.1 on 2026-09-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storenews',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'store news'},
        ),
    ]
